# Abstract

In order to find significant trends and insights that can help inform business decisions with a health focus, this case study examines Fitbit user activity data. R was used for the entire analysis, demonstrating its adaptability for data transformation, cleaning, reporting, and visualisation. I approached the project with a focus on both user-centred data interpretation and clarity. Importing and cleaning the dataset, producing summary statistics, and designing visualisations to identify patterns in calorie expenditure, sedentary behaviour, and activity levels were crucial visualisation steps. The results point to ways to enhance user involvement and provide tailored health advice. This project demonstrates the usefulness of R in end-to-end data analysis and showcases my growth as a data analyst.

# Step 1 - Ask

## Business Task

Analyse smart device fitness data to uncover customer usage patterns and trends, then provide high-level marketing recommendations for one Bellabeat product based on these insights.

## Key Questions

1. What are some trends in smart device usage?
2. How could these trends apply to Bellabeat customers?
3. How could these trends influence Bellabeat’s marketing strategy?

# Step 2 – Prepare

## Data Source

The FitBit Fitness Tracker Data used for this case study was obtained from Kaggle, provided by Mobius. This dataset tracks the daily activity of 30 FitBit users, including steps, calories, sleep, and heart rate.

The data was split into multiple CSV files covering daily steps and calories, sleep patterns, heart rate measurements, and activity intensity levels.

## ROCCC Analysis
Reliable: the data sourced from a reputable platform (Kaggle), making it accurate, complete and unbiased.

Original: the data source is original, as the participants consented to the submission of their personal tracker data.

Comprehensive: the data source contains all critical information needed to answer the question.

Current: the data isn't as it was gathered in 2016.

Cited: the data source is acknowledged in Kaggle.

# Step 3 – Process

In [1]:
# Loading Packages

library(tidyverse)
library(lubridate)
library(tidyr)
library(dplyr)
library(ggplot2)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [3]:
# Importing Datasets

library(readr)

daily_activity <- read_csv("/kaggle/input/fitbit/mturkfitbit_export_4.12.16-5.12.16/Fitabase Data 4.12.16-5.12.16/dailyActivity_merged.csv", show_col_types = FALSE)
daily_calories <- read_csv("/kaggle/input/fitbit/mturkfitbit_export_4.12.16-5.12.16/Fitabase Data 4.12.16-5.12.16/dailyCalories_merged.csv", show_col_types = FALSE) 
hourly_calories <- read_csv("/kaggle/input/fitbit/mturkfitbit_export_4.12.16-5.12.16/Fitabase Data 4.12.16-5.12.16/hourlyCalories_merged.csv", show_col_types = FALSE)
hourly_steps <- read_csv("/kaggle/input/fitbit/mturkfitbit_export_4.12.16-5.12.16/Fitabase Data 4.12.16-5.12.16/hourlySteps_merged.csv", show_col_types = FALSE)
sleep_data <- read_csv("/kaggle/input/fitbit/mturkfitbit_export_4.12.16-5.12.16/Fitabase Data 4.12.16-5.12.16/sleepDay_merged.csv", show_col_types = FALSE)

In [4]:
# Reviewing Data Structure

head(daily_activity)
head(daily_calories)
head(hourly_calories)
head(hourly_steps)
head(sleep_data)

str(daily_activity)
str(daily_calories)
str(hourly_calories)
str(hourly_steps)
str(sleep_data)

  Id         ActivityDate TotalSteps TotalDistance TrackerDistance
1 1503960366 4/12/2016    13162      8.50          8.50
2 1503960366 4/13/2016    10735      6.97          6.97
3 1503960366 4/14/2016    10460      6.74          6.74
4 1503960366 4/15/2016     9762      6.28          6.28
5 1503960366 4/16/2016    12669      8.16          8.16
6 1503960366 4/17/2016     9705      6.48          6.48
  LoggedActivitiesDistance VeryActiveDistance ModeratelyActiveDistance
1 0                        1.88               0.55
2 0                        1.57               0.69
3 0                        2.44               0.40
4 0                        2.14               1.26
5 0                        2.71               0.41
6 0                        3.19               0.78
  LightActiveDistance SedentaryActiveDistance VeryActiveMinutes
1 6.06                0                       25
2 4.71                0                       21
3 3.91                0                       30
4 2.83                0                       29
5 5.04                0                       36
6 2.51                0                       38
  FairlyActiveMinutes LightlyActiveMinutes SedentaryMinutes Calories
1 13                  328                   728             1985
2 19                  217                   776             1797
3 11                  181                  1218             1776
4 34                  209                   726             1745
5 10                  221                   773             1863
6 20                  164                   539             1728

  Id         ActivityDay Calories
1 1503960366 4/12/2016   1985
2 1503960366 4/13/2016   1797
3 1503960366 4/14/2016   1776
4 1503960366 4/15/2016   1745
5 1503960366 4/16/2016   1863
6 1503960366 4/17/2016   1728

  Id         ActivityHour          Calories
1 1503960366 4/12/2016 12:00:00 AM 81
2 1503960366 4/12/2016 1:00:00 AM  61
3 1503960366 4/12/2016 2:00:00 AM  59
4 1503960366 4/12/2016 3:00:00 AM  47
5 1503960366 4/12/2016 4:00:00 AM  48
6 1503960366 4/12/2016 5:00:00 AM  48

  Id         ActivityHour          StepTotal
1 1503960366 4/12/2016 12:00:00 AM 373
2 1503960366 4/12/2016 1:00:00 AM  160
3 1503960366 4/12/2016 2:00:00 AM  151
4 1503960366 4/12/2016 3:00:00 AM    0
5 1503960366 4/12/2016 4:00:00 AM    0
6 1503960366 4/12/2016 5:00:00 AM    0

  Id         SleepDay              TotalSleepRecords TotalMinutesAsleep
1 1503960366 4/12/2016 12:00:00 AM 1                 327
2 1503960366 4/13/2016 12:00:00 AM 2                 384
3 1503960366 4/15/2016 12:00:00 AM 1                 412
4 1503960366 4/16/2016 12:00:00 AM 2                 340
5 1503960366 4/17/2016 12:00:00 AM 1                 700
6 1503960366 4/19/2016 12:00:00 AM 1                 304
  TotalTimeInBed
1 346
2 407
3 442
4 367
5 712
6 320

spc_tbl_ [940 × 15] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ Id                      : num [1:940] 1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
 $ ActivityDate            : chr [1:940] "4/12/2016" "4/13/2016" "4/14/2016" "4/15/2016" ...
 $ TotalSteps              : num [1:940] 13162 10735 10460 9762 12669 ...
 $ TotalDistance           : num [1:940] 8.5 6.97 6.74 6.28 8.16 ...
 $ TrackerDistance         : num [1:940] 8.5 6.97 6.74 6.28 8.16 ...
 $ LoggedActivitiesDistance: num [1:940] 0 0 0 0 0 0 0 0 0 0 ...
 $ VeryActiveDistance      : num [1:940] 1.88 1.57 2.44 2.14 2.71 ...
 $ ModeratelyActiveDistance: num [1:940] 0.55 0.69 0.4 1.26 0.41 ...
 $ LightActiveDistance     : num [1:940] 6.06 4.71 3.91 2.83 5.04 ...
 $ SedentaryActiveDistance : num [1:940] 0 0 0 0 0 0 0 0 0 0 ...
 $ VeryActiveMinutes       : num [1:940] 25 21 30 29 36 38 42 50 28 19 ...
 $ FairlyActiveMinutes     : num [1:940] 13 19 11 34 10 20 16 31 12 8 ...
 $ LightlyActiveMinutes    : num [1:940] 328 217 181 209 221 164 233 264 205 211 ...
 $ SedentaryMinutes        : num [1:940] 728 776 1218 726 773 ...
 $ Calories                : num [1:940] 1985 1797 1776 1745 1863 ...
 - attr(*, "spec")=
  .. cols(
  ..   Id = col_double(),
  ..   ActivityDate = col_character(),
  ..   TotalSteps = col_double(),
  ..   TotalDistance = col_double(),
  ..   TrackerDistance = col_double(),
  ..   LoggedActivitiesDistance = col_double(),
  ..   VeryActiveDistance = col_double(),
  ..   ModeratelyActiveDistance = col_double(),
  ..   LightActiveDistance = col_double(),
  ..   SedentaryActiveDistance = col_double(),
  ..   VeryActiveMinutes = col_double(),
  ..   FairlyActiveMinutes = col_double(),
  ..   LightlyActiveMinutes = col_double(),
  ..   SedentaryMinutes = col_double(),
  ..   Calories = col_double()
  .. )
 - attr(*, "problems")=<externalptr>
spc_tbl_ [940 × 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ Id         : num [1:940] 1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
 $ ActivityDay: chr [1:940] "4/12/2016" "4/13/2016" "4/14/2016" "4/15/2016" ...
 $ Calories   : num [1:940] 1985 1797 1776 1745 1863 ...
 - attr(*, "spec")=
  .. cols(
  ..   Id = col_double(),
  ..   ActivityDay = col_character(),
  ..   Calories = col_double()
  .. )
 - attr(*, "problems")=<externalptr>
spc_tbl_ [22,099 × 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ Id          : num [1:22099] 1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
 $ ActivityHour: chr [1:22099] "4/12/2016 12:00:00 AM" "4/12/2016 1:00:00 AM" "4/12/2016 2:00:00 AM" "4/12/2016 3:00:00 AM" ...
 $ Calories    : num [1:22099] 81 61 59 47 48 48 48 47 68 141 ...
 - attr(*, "spec")=
  .. cols(
  ..   Id = col_double(),
  ..   ActivityHour = col_character(),
  ..   Calories = col_double()
  .. )
 - attr(*, "problems")=<externalptr>
spc_tbl_ [22,099 × 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ Id          : num [1:22099] 1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
 $ ActivityHour: chr [1:22099] "4/12/2016 12:00:00 AM" "4/12/2016 1:00:00 AM" "4/12/2016 2:00:00 AM" "4/12/2016 3:00:00 AM" ...
 $ StepTotal   : num [1:22099] 373 160 151 0 0 ...
 - attr(*, "spec")=
  .. cols(
  ..   Id = col_double(),
  ..   ActivityHour = col_character(),
  ..   StepTotal = col_double()
  .. )
 - attr(*, "problems")=<externalptr>
spc_tbl_ [413 × 5] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ Id                : num [1:413] 1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
 $ SleepDay          : chr [1:413] "4/12/2016 12:00:00 AM" "4/13/2016 12:00:00 AM" "4/15/2016 12:00:00 AM" "4/16/2016 12:00:00 AM" ...
 $ TotalSleepRecords : num [1:413] 1 2 1 2 1 1 1 1 1 1 ...
 $ TotalMinutesAsleep: num [1:413] 327 384 412 340 700 304 360 325 361 430 ...
 $ TotalTimeInBed    : num [1:413] 346 407 442 367 712 320 377 364 384 449 ...
 - attr(*, "spec")=
  .. cols(
  ..   Id = col_double(),
  ..   SleepDay = col_character(),
  ..   TotalSleepRecords = col_double(),
  ..   TotalMinutesAsleep = col_double(),
  ..   TotalTimeInBed = col_double()
  .. )
 - attr(*, "problems")=<externalptr>

## Cleaning

## Cleaning Column Names

In [5]:
#column check for all datasets
colnames(daily_activity)
colnames(sleep_data)
colnames(hourly_calories)
colnames(hourly_steps)

 [1] "Id"                       "ActivityDate"
 [3] "TotalSteps"               "TotalDistance"
 [5] "TrackerDistance"          "LoggedActivitiesDistance"
 [7] "VeryActiveDistance"       "ModeratelyActiveDistance"
 [9] "LightActiveDistance"      "SedentaryActiveDistance"
[11] "VeryActiveMinutes"        "FairlyActiveMinutes"
[13] "LightlyActiveMinutes"     "SedentaryMinutes"
[15] "Calories"

[1] "Id"                 "SleepDay"           "TotalSleepRecords"
[4] "TotalMinutesAsleep" "TotalTimeInBed"

[1] "Id"           "ActivityHour" "Calories"

[1] "Id"           "ActivityHour" "StepTotal"

In [6]:
names(daily_activity)
names(sleep_data)
names(hourly_calories)
names(hourly_steps)

 [1] "Id"                       "ActivityDate"
 [3] "TotalSteps"               "TotalDistance"
 [5] "TrackerDistance"          "LoggedActivitiesDistance"
 [7] "VeryActiveDistance"       "ModeratelyActiveDistance"
 [9] "LightActiveDistance"      "SedentaryActiveDistance"
[11] "VeryActiveMinutes"        "FairlyActiveMinutes"
[13] "LightlyActiveMinutes"     "SedentaryMinutes"
[15] "Calories"

[1] "Id"                 "SleepDay"           "TotalSleepRecords"
[4] "TotalMinutesAsleep" "TotalTimeInBed"

[1] "Id"           "ActivityHour" "Calories"

[1] "Id"           "ActivityHour" "StepTotal"

In [7]:
library(dplyr)
library(janitor)

#Clean column names for all datasets
daily_activity <- daily_activity %>% clean_names()
sleep_data <- sleep_data %>% clean_names()
hourly_calories <- hourly_calories %>% clean_names()
hourly_steps <- hourly_steps %>% clean_names()

Attaching package: ‘janitor’


The following objects are masked from ‘package:stats’:

    chisq.test, fisher.test

## Convert Date-Time Columns

In [9]:
library(dplyr)
library(lubridate)

# daily_activity: convert activity_date
daily_activity <- daily_activity %>%
  mutate(date = mdy(activity_date))

# sleep_data: convert sleep_day
sleep_data <- sleep_data %>%
  mutate(date = mdy_hms(sleep_day))

# hourly_calories: convert activity_hour
hourly_calories <- hourly_calories %>%
  mutate(activity_hour = mdy_hms(activity_hour),
         date = as_date(activity_hour))

# hourly_steps: convert activity_hour
hourly_steps <- hourly_steps %>%
  mutate(activity_hour = mdy_hms(activity_hour),
         date = as_date(activity_hour))

Warning message:
“There was 1 warning in `mutate()`.
ℹ In argument: `activity_hour = mdy_hms(activity_hour)`.
Caused by warning:
! All formats failed to parse. No formats found.”
Warning message:
“There was 1 warning in `mutate()`.
ℹ In argument: `activity_hour = mdy_hms(activity_hour)`.
Caused by warning:
! All formats failed to parse. No formats found.”

## Check And Remove Duplicates And Null

In [ ]:
library(dplyr)

# Daily Activity
daily_activity <- daily_activity %>%
  distinct() %>%          # remove duplicates
  drop_na()               # remove rows with any NA values

# Sleep Data
sleep_data <- sleep_data %>%
  distinct() %>%
  drop_na()

# Hourly Calories
hourly_calories <- hourly_calories %>%
  distinct() %>%
  drop_na()

# Hourly Steps
hourly_steps <- hourly_steps %>%
  distinct() %>%
  drop_na()

In [ ]:
#Rechecking for null values 
sum(is.na(daily_activity))
sum(is.na(sleep_data))
sum(is.na(hourly_calories))
sum(is.na(hourly_steps))

In [ ]:
#Rechecking for missing values 
colSums(is.na(daily_activity))
colSums(is.na(sleep_data))
colSums(is.na(hourly_calories))
colSums(is.na(hourly_steps))

## Merge Datasets

In [ ]:
library(dplyr)
library(lubridate)

daily_sleep <- merge(daily_activity, sleep_data,
                     by = c("id", "date"),
                     all = TRUE)   

hourly_data <- merge(hourly_calories, hourly_steps,
                     by = c("id", "activity_hour", "date"),
                     all = TRUE)

# **Step 4 – Analyse**

Average Step Per Day of the Week

In [ ]:
library(dplyr)
library(lubridate)

#Add weekday column and calculate average steps
avg_steps_by_day <- daily_activity %>%
  mutate(weekday = wday(date, label = TRUE, abbr = FALSE)) %>%  # Extract weekday name
  group_by(weekday) %>%
  summarise(avg_steps = mean(total_steps, na.rm = TRUE)) %>%
  arrange(match(weekday, c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")))

overall_averages <- daily_activity %>%
  summarise(
    avg_steps = mean(total_steps, na.rm = TRUE),
    avg_calories = mean(calories, na.rm = TRUE)
  )

overall_averages

avg_steps_by_day

# **Step 5 – Share**

Data Visualisation and Key Insights

In [ ]:
library(ggplot2)

ggplot(daily_activity, aes(x = total_steps, y = calories)) +
  geom_point(alpha = 0.6, colour = "steelblue") +   
  geom_smooth(method = "lm", se = FALSE, colour = "red") + 
  labs(title = "Scatter Plot of Total Steps vs Calories",
       x = "Total Steps",
       y = "Calories Burned") +
  theme_minimal()

**Insights**

* Users' average daily steps are below the recommended 10,000 steps. This suggests that most users are not highly active.
* Your scatter plot shows that the number of steps taken and the number of calories burnt are closely linked, but calories burnt can also vary depending on the intensity of activity, not just step count.
* Friday, Saturday, and Sunday tend to show higher activity, while weekdays show lower step counts, likely due to sedentary activities such as sitting at work.
* According to sleep data, many users get less than the recommended 7–8 hours of sleep per night.
* Users are active before and after work because step counts and calorie burn peak in the morning (7–9 am) and evening (5–8 pm).

# **Step 6 – Act**

## Bellabeat's Recommendations

1. **Low Average Daily Steps (<10,000)**

* Introduce step-based challenges in the Bellabeat app (e.g., “7-Day 10k Challenge”) to encourage users to gradually reach recommended activity levels.

* Create social challenges in the app, such as step streaks and weekend wellness challenges, to motivate users through peer accountability.

* Promote Bellabeat products as daily motivation partners that help women close the gap between current habits and global health recommendations.

  

2. **Steps vs Calories (Intensity Matters)**

* Use Bellabeat’s app to highlight intensity tracking, not just step counts, through reminders to incorporate brisk walking or short workouts.

* Emphasise that Bellabeat devices do more than count steps — they provide meaningful insights into how activity quality impacts calorie burn and health outcomes.

  

3. **Weekend Peaks, Weekday Dips**

* Offer weekday activity reminders (stand up, stretch, 10-minute walks) through app notifications.

* Campaign around “Wellness at Work”, showing how Bellabeat products support healthier weekday routines, not just weekend fitness.

  

4. **Inadequate Sleep (<7 to 8 hours)**

* Enhance or highlight Bellabeat’s sleep monitoring features (bedtime reminders, sleep quality scores).

* Position Bellabeat as a holistic wellness companion that improves not only fitness but also rest, recovery, and long-term health.

* Share educational content on Bellabeat’s social media about sleep hygiene, active commuting, and micro-activities during workdays.



5. **Morning & Evening Activity Peaks**

* Integrate “Morning Boost” and “Evening Wind-Down” routines in the Bellabeat app, pairing reminders with activity suggestions (morning yoga, evening walks).

* Market Bellabeat as a brand that fits naturally into daily routines, encouraging healthier habits before and after work.